# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
- group: serverless

pool:
  vmImage: ubuntu-latest

stages:
- stage: ContinousIntegration
  jobs:
  - job: ContinousIntegration
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'
    - script: |
        node -v
        npm -v
        npm install
        npm run test:coverage
      displayName: UnitTest
    - script: |
        npm install eslint --save-dev
        npm run lint
      displayName: StaticAnalysis
    - script: |
        node -v
        npm -v
        npm install -g serverless
        sls config credentials --provider aws --key $(awsID) --secret $(awsSecret)
        sls package
        ls -al .serverless
      displayName: Package
    - script: sls deploy
      displayName: Deploy
